import type { Opportunity } from "./opportunities"

// List of causes for filtering
export const causes = [
  "Environment",
  "Education",
  "Health",
  "Homelessness",
  "Animal Welfare",
  "Community Development",
  "Elderly Care",
  "Disaster Relief",
]

// List of commitment levels for filtering
export const commitmentLevels = ["One-time", "Weekly", "Monthly", "Flexible"]

// Mock data for volunteer opportunities
export const opportunities: Opportunity[] = [
  {
    id: "1",
    title: "Beach Cleanup Day",
    organization: "Ocean Conservancy",
    description: "Join us for a day of cleaning up the local beach and protecting marine life.",
    location: "Coastal Beach Park",
    date: "2025-04-15",
    commitmentLevel: "One-time",
    cause: "Environment",
    imageUrl: "/placeholder.svg?height=192&width=384&text=Beach+Cleanup",
  },
  {
    id: "2",
    title: "Literacy Tutoring",
    organization: "Reading Partners",
    description: "Help elementary school students improve their reading skills.",
    location: "Lincoln Elementary School",
    date: "2025-04-20",
    commitmentLevel: "Weekly",
    cause: "Education",
    imageUrl: "/placeholder.svg?height=192&width=384&text=Literacy+Tutoring",
  },
  {
    id: "3",
    title: "Food Bank Assistant",
    organization: "Community Food Bank",
    description: "Sort and package food donations for distribution to those in need.",
    location: "Downtown Food Bank",
    date: "2025-04-18",
    commitmentLevel: "Flexible",
    cause: "Homelessness",
    imageUrl: "/placeholder.svg?height=192&width=384&text=Food+Bank",
  },
  {
    id: "4",
    title: "Animal Shelter Helper",
    organization: "Paws & Claws Rescue",
    description: "Help care for rescued animals and assist with adoption events.",
    location: "Paws & Claws Shelter",
    date: "2025-04-22",
    commitmentLevel: "Weekly",
    cause: "Animal Welfare",
    imageUrl: "/placeholder.svg?height=192&width=384&text=Animal+Shelter",
  },
  {
    id: "5",
    title: "Community Garden Project",
    organization: "Green Spaces Initiative",
    description: "Help plant and maintain a community garden that provides fresh produce to local families.",
    location: "Riverside Community Center",
    date: "2025-04-25",
    commitmentLevel: "Monthly",
    cause: "Community Development",
    imageUrl: "/placeholder.svg?height=192&width=384&text=Community+Garden",
  },
  {
    id: "6",
    title: "Senior Companion Program",
    organization: "Elder Care Alliance",
    description: "Provide companionship and assistance to seniors in the community.",
    location: "Sunshine Senior Living",
    date: "2025-04-19",
    commitmentLevel: "Weekly",
    cause: "Elderly Care",
    imageUrl: "/placeholder.svg?height=192&width=384&text=Senior+Companion",
  },
  {
    id: "7",
    title: "Health Clinic Assistant",
    organization: "Community Health Network",
    description: "Assist healthcare professionals at a free community health clinic.",
    location: "Westside Health Center",
    date: "2025-04-30",
    commitmentLevel: "Monthly",
    cause: "Health",
    imageUrl: "/placeholder.svg?height=192&width=384&text=Health+Clinic",
  },
  {
    id: "8",
    title: "Disaster Relief Volunteer",
    organization: "Emergency Response Team",
    description: "Help with disaster preparedness and relief efforts in the community.",
    location: "City Emergency Center",
    date: "2025-05-05",
    commitmentLevel: "Flexible",
    cause: "Disaster Relief",
    imageUrl: "/placeholder.svg?height=192&width=384&text=Disaster+Relief",
  },
  {
    id: "9",
    title: "Habitat Construction Volunteer",
    organization: "Habitat for Humanity",
    description: "Help build homes for families in need in your community.",
    location: "Eastside Construction Site",
    date: "2025-05-10",
    commitmentLevel: "One-time",
    cause: "Community Development",
    imageUrl: "/placeholder.svg?height=192&width=384&text=Habitat+Construction",
  },
  {
    id: "10",
    title: "STEM Education Mentor",
    organization: "Future Scientists",
    description: "Mentor students in science, technology, engineering, and math projects.",
    location: "Washington High School",
    date: "2025-05-15",
    commitmentLevel: "Weekly",
    cause: "Education",
    imageUrl: "/placeholder.svg?height=192&width=384&text=STEM+Education",
  },
  {
    id: "11",
    title: "Wildlife Conservation Project",
    organization: "Nature Conservancy",
    description: "Assist with wildlife monitoring and habitat restoration projects.",
    location: "Willow Creek Nature Preserve",
    date: "2025-05-20",
    commitmentLevel: "Monthly",
    cause: "Environment",
    imageUrl: "/placeholder.svg?height=192&width=384&text=Wildlife+Conservation",
  },
  {
    id: "12",
    title: "Homeless Shelter Support",
    organization: "Shelter Alliance",
    description: "Help prepare meals and provide support at a local homeless shelter.",
    location: "Hope Homeless Shelter",
    date: "2025-05-25",
    commitmentLevel: "Flexible",
    cause: "Homelessness",
    imageUrl: "/placeholder.svg?height=192&width=384&text=Homeless+Shelter",
  },
]

